#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Claude Code / Codex / OpenCode 会话转换脚本 (四方向)

用法 (不带参数运行进入交互菜单):
  python session_convert.py codex2claude <rollout.jsonl>      # Codex -> Claude
  python session_convert.py claude2codex <session.jsonl>      # Claude -> Codex
  python session_convert.py opencode2codex <ses_id>           # OpenCode -> Codex
  python session_convert.py codex2opencode <rollout.jsonl>    # Codex -> OpenCode 导出
  各命令均支持 --latest;  list [codex|claude|opencode] 列出可转换的会话

默认把结果直接"安装"到目标工具的会话目录, 使其出现在对方的历史会话列表里;
用 -o <文件> 可只输出到指定文件而不安装。

格式说明 (基于实际文件逆向):
  Codex rollout (~/.codex/sessions/YYYY/MM/DD/rollout-*.jsonl):
    每行 {timestamp, type, payload}
    type: session_meta / response_item / event_msg / turn_context / world_state
    response_item.payload.type: message(role=user|assistant|developer,
      content=[{input_text|output_text}]) / reasoning(summary=[summary_text]) /
      custom_tool_call|function_call / custom_tool_call_output|function_call_output
  Claude session (~/.claude/projects/<项目名>/<uuid>.jsonl):
    每行一条记录, type: user / assistant / attachment / ai-title 等
    user.message.content = 字符串 或 [{type:tool_result,...}]
    assistant.message.content = [{type: thinking|text|tool_use}]
    记录之间用 parentUuid -> uuid 链接
"""

import argparse
import base64
import glob
import hashlib
import json
import os
import re
import sys
import uuid
from datetime import datetime, timezone

# 控制台编码兜底: 在画不出中文的代码页(如 cp1252)下输出提示时不崩溃
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(errors="replace")
    except (AttributeError, OSError):
        pass

HOME = os.path.expanduser("~")
CODEX_SESSIONS_DIR = os.path.join(HOME, ".codex", "sessions")
CODEX_INDEX_FILE = os.path.join(HOME, ".codex", "session_index.jsonl")
CLAUDE_PROJECTS_DIR = os.path.join(HOME, ".claude", "projects")
# Claude 桌面应用的会话注册目录 (历史列表只读这里, 不扫描 CLI 会话目录)
CLAUDE_DESKTOP_DIR = os.path.join(
    os.environ.get("APPDATA", ""), "Claude", "claude-code-sessions")
CLAUDE_VERSION = "2.1.219"  # 写入 claude 记录的 version 字段
CONFLICT_MODES = ("skip", "overwrite", "fork", "update")

# Codex 会把 AGENTS.md / 环境上下文等包装成 user 消息塞进对话,
# 转换成 Claude 会话时默认跳过这些非人类输入
CONTEXT_PREFIXES = (
    "<app-context>", "<user_instructions>", "<environment_context>",
    "<turn-state>", "<permissions", "# AGENTS.md", "﻿# AGENTS.md",
    "<collaboration_mode>", "<current-datetime>", "<in-app-browser-context",
)

# Claude 会把斜杠命令 / 本地命令输出 / 系统提醒等记录成 user 消息,
# 转换成 Codex 会话时默认跳过
CLAUDE_NOISE_PREFIXES = (
    "<command-name>", "<command-message>", "<local-command-stdout>",
    "<local-command-caveat>", "<system-reminder>", "<task-notification>",
    "Caveat: The messages below were generated by the user while running local commands",
    "[Request interrupted by user",
)


def read_jsonl(path):
    records = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                pass  # 跳过损坏的行
    return records


def _stable_hex(namespace, source_id, length=32):
    return hashlib.sha256(
        ("codex-session-bridge:%s:%s" % (namespace, source_id)).encode("utf-8")
    ).hexdigest()[:length]


def stable_codex_id(source_id):
    try:
        return str(uuid.UUID(source_id))
    except (ValueError, AttributeError, TypeError):
        return str(uuid.UUID(_stable_hex("codex", source_id), version=5))


def stable_opencode_id(source_id):
    if isinstance(source_id, str) and source_id.startswith("ses_"):
        return source_id
    return "ses_" + _stable_hex("opencode", source_id, 26)


def _is_within(path, root):
    try:
        return os.path.commonpath(
            (os.path.abspath(path), os.path.abspath(root))) == os.path.abspath(root)
    except ValueError:
        return False


def _fork_output_path(path, target_id):
    stem, suffix = os.path.splitext(path)
    return "%s-%s%s" % (stem, target_id[:8], suffix)


def _resolve_output_conflict(path, mode, fork_id_factory=None,
                             fork_path_factory=None):
    if not os.path.exists(path):
        return path, None, False
    if mode == "skip":
        print("目标已存在, 已跳过: %s" % path)
        return path, None, True
    if mode == "overwrite":
        return path, None, False
    if mode == "update":
        print("独立脚本无法证明目标没有续聊, 为安全起见已跳过: %s" % path)
        print("如确认允许覆盖, 请显式使用 --on-conflict overwrite")
        return path, None, True
    if mode == "fork":
        if fork_id_factory is None:
            raise ValueError("fork 模式缺少目标 ID 生成器")
        target_id = fork_id_factory()
        fork_path = (fork_path_factory(target_id) if fork_path_factory
                     else _fork_output_path(path, target_id))
        while os.path.exists(fork_path):
            target_id = fork_id_factory()
            fork_path = (fork_path_factory(target_id) if fork_path_factory
                         else _fork_output_path(path, target_id))
        return fork_path, target_id, False
    raise ValueError("未知冲突策略: %s" % mode)


def write_jsonl(path, records, overwrite=False):
    parent = os.path.dirname(path)
    if parent:  # -o 传相对文件名时 dirname 为空, makedirs('') 会报错
        os.makedirs(parent, exist_ok=True)
    if os.path.exists(path) and not overwrite:
        raise FileExistsError("Refusing to overwrite existing file: %s" % path)
    temp_path = path + ".session-convert.tmp"
    with open(temp_path, "w", encoding="utf-8", newline="\n") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    os.replace(temp_path, path)


def write_json(path, value, overwrite=False):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    if os.path.exists(path) and not overwrite:
        raise FileExistsError("Refusing to overwrite existing file: %s" % path)
    temp_path = path + ".session-convert.tmp"
    with open(temp_path, "w", encoding="utf-8") as f:
        json.dump(value, f, ensure_ascii=False, indent=2)
    os.replace(temp_path, path)


def upsert_codex_index(session_id, title):
    updated = {"id": session_id, "thread_name": title, "updated_at": now_iso()}
    lines = []
    if os.path.exists(CODEX_INDEX_FILE):
        with open(CODEX_INDEX_FILE, encoding="utf-8-sig") as f:
            lines = f.readlines()
    result_lines = []
    replaced = False
    for line in lines:
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            entry = None
        if isinstance(entry, dict) and entry.get("id") == session_id:
            if not replaced:
                result_lines.append(json.dumps(updated, ensure_ascii=False) + "\n")
                replaced = True
            continue
        result_lines.append(line if line.endswith("\n") else line + "\n")
    if not replaced:
        result_lines.append(json.dumps(updated, ensure_ascii=False) + "\n")
    parent = os.path.dirname(CODEX_INDEX_FILE)
    if parent:
        os.makedirs(parent, exist_ok=True)
    temp_path = CODEX_INDEX_FILE + ".session-convert.tmp"
    with open(temp_path, "w", encoding="utf-8", newline="\n") as f:
        f.writelines(result_lines)
    os.replace(temp_path, CODEX_INDEX_FILE)


def now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def sanitize_project_dir(cwd):
    """Claude 的项目目录名: 路径中非字母数字的字符全部替换为 '-'"""
    return re.sub(r"[^A-Za-z0-9]", "-", cwd)


def content_to_text(content):
    """把 codex 的 content(字符串或 [{type, text}] 列表)拍平成纯文本"""
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    parts = []
    for block in content:
        if isinstance(block, dict):
            parts.append(block.get("text", ""))
        else:
            parts.append(str(block))
    return "".join(parts)


def content_images(content):
    """提取 codex content 里的 input_image (data URL) -> [(media_type, base64串)]"""
    images = []
    if not isinstance(content, list):
        return images
    for block in content:
        if isinstance(block, dict) and block.get("type") == "input_image":
            url = block.get("image_url", "")
            if isinstance(url, str) and url.startswith("data:") and ";base64," in url:
                media, data = url[5:].split(";base64,", 1)
                images.append((media or "image/png", data))
    return images


def latest_file(pattern_dir, glob_pat):
    files = glob.glob(os.path.join(pattern_dir, glob_pat), recursive=True)
    files = [f for f in files if os.path.isfile(f)]
    if not files:
        return None
    return max(files, key=os.path.getmtime)


# ---------------------------------------------------------------------------
# Codex -> Claude
# ---------------------------------------------------------------------------

def codex_to_claude(src, out_path=None, install=True, include_context=False,
                    reasoning_mode="thinking", title=None, override_cwd=None,
                    on_conflict="skip"):
    records = read_jsonl(src)

    meta = next((r["payload"] for r in records if r.get("type") == "session_meta"), {})
    cwd = override_cwd or meta.get("cwd", os.getcwd())
    session_id = meta.get("session_id") or meta.get("id") or str(uuid.uuid4())

    project_dir = os.path.join(CLAUDE_PROJECTS_DIR, sanitize_project_dir(cwd))
    if install and out_path is None:
        out_path = os.path.join(project_dir, session_id + ".jsonl")
        out_path, fork_id, skipped = _resolve_output_conflict(
            out_path, on_conflict, lambda: str(uuid.uuid4()),
            lambda target_id: os.path.join(project_dir, target_id + ".jsonl"))
        if skipped:
            return out_path
        if fork_id:
            session_id = fork_id
    elif out_path is not None:
        out_path, fork_id, skipped = _resolve_output_conflict(
            out_path, on_conflict, lambda: str(uuid.uuid4()))
        if skipped:
            return out_path
        if fork_id:
            session_id = fork_id

    out = []
    parent_uuid = None
    prompt_id = str(uuid.uuid4())
    first_user_text = None
    # 同一个 codex 回合里的连续 assistant 块共享一个 message id
    cur_msg_id = None
    # Codex 会在每次恢复会话时重复记录未回答的用户输入, 用于去重
    last_human_text = None

    def base_fields(ts):
        return {
            "parentUuid": parent_uuid,
            "isSidechain": False,
            "userType": "external",
            "cwd": cwd,
            "sessionId": session_id,
            "version": CLAUDE_VERSION,
            "gitBranch": "",
            "timestamp": ts,
        }

    def emit_user(ts, content, is_human):
        nonlocal parent_uuid, cur_msg_id
        rec = base_fields(ts)
        rec.update({
            "type": "user",
            "promptId": prompt_id,
            "message": {"role": "user", "content": content},
            "uuid": str(uuid.uuid4()),
        })
        if is_human:
            rec["origin"] = {"kind": "human"}
        out.append(rec)
        parent_uuid = rec["uuid"]
        cur_msg_id = None  # 新一轮, 下个 assistant 块用新 message id

    def emit_assistant(ts, block):
        nonlocal parent_uuid, cur_msg_id
        if cur_msg_id is None:
            cur_msg_id = "msg_conv_" + uuid.uuid4().hex[:24]
        rec = base_fields(ts)
        rec.update({
            "type": "assistant",
            "message": {
                "model": meta.get("model", "converted-from-codex"),
                "id": cur_msg_id,
                "type": "message",
                "role": "assistant",
                "content": [block],
                "stop_reason": None,
                "stop_sequence": None,
                "usage": {"input_tokens": 0, "output_tokens": 0},
            },
            "uuid": str(uuid.uuid4()),
        })
        out.append(rec)
        parent_uuid = rec["uuid"]

    for rec in records:
        if rec.get("type") != "response_item":
            continue
        p = rec.get("payload", {})
        pt = p.get("type")
        ts = rec.get("timestamp") or now_iso()

        if pt == "message":
            role = p.get("role")
            text = content_to_text(p.get("content"))
            images = content_images(p.get("content")) if role == "user" else []
            if not text.strip() and not images:
                continue
            if role == "user":
                stripped = text.lstrip()
                if not include_context and stripped.startswith(CONTEXT_PREFIXES):
                    continue
                if not images and text.strip() == last_human_text:
                    continue  # 恢复会话时重复记录的同一条输入(可能差个换行)
                last_human_text = text.strip()
                prompt_id = str(uuid.uuid4())
                if first_user_text is None and text.strip():
                    first_user_text = text
                if images:
                    blocks = [{"type": "image",
                               "source": {"type": "base64", "media_type": m,
                                          "data": d}} for m, d in images]
                    if text.strip():
                        blocks.append({"type": "text", "text": text})
                    emit_user(ts, blocks, is_human=True)
                else:
                    emit_user(ts, text, is_human=True)
            elif role == "assistant":
                last_human_text = None
                emit_assistant(ts, {"type": "text", "text": text})
            else:  # developer / system: 默认跳过
                if include_context:
                    emit_user(ts, "[%s context]\n%s" % (role, text), is_human=False)

        elif pt == "reasoning":
            if reasoning_mode == "skip":
                continue
            summary = "\n\n".join(
                s.get("text", "") for s in p.get("summary", []) if s.get("text")
            )
            if not summary.strip():
                continue
            if reasoning_mode == "text":
                emit_assistant(ts, {"type": "text", "text": summary})
            else:
                emit_assistant(ts, {"type": "thinking", "thinking": summary,
                                    "signature": ""})

        elif pt in ("custom_tool_call", "function_call"):
            name = p.get("name", "tool")
            call_id = p.get("call_id") or p.get("id") or "call_" + uuid.uuid4().hex[:20]
            if pt == "function_call":
                raw = p.get("arguments", "")
                try:
                    tool_input = json.loads(raw) if raw else {}
                    if not isinstance(tool_input, dict):
                        tool_input = {"arguments": tool_input}
                except json.JSONDecodeError:
                    tool_input = {"arguments": raw}
            else:
                # custom_tool_call 的 input 是自由格式字符串(如 JS 代码)
                tool_input = {"input": p.get("input", "")}
            emit_assistant(ts, {"type": "tool_use", "id": call_id,
                                "name": name, "input": tool_input})

        elif pt in ("custom_tool_call_output", "function_call_output"):
            call_id = p.get("call_id") or ""
            text = content_to_text(p.get("output"))
            emit_user(ts, [{"tool_use_id": call_id, "type": "tool_result",
                            "content": text}], is_human=False)

    if not out:
        sys.exit("没有可转换的对话内容: %s" % src)

    # 会话标题, 显示在 Claude 的历史会话列表里
    if title:
        out.append({"type": "custom-title", "customTitle": title,
                    "sessionId": session_id})

    if out_path is None:
        out_path = os.path.splitext(src)[0] + ".claude.jsonl"
    write_jsonl(out_path, out, overwrite=on_conflict == "overwrite")

    n_user = sum(1 for r in out if r["type"] == "user" and isinstance(r["message"]["content"], str))
    print("Codex -> Claude 转换完成")
    print("  来源: %s" % src)
    print("  输出: %s" % out_path)
    print("  记录: %d 条 (人类消息 %d 条), cwd=%s" % (len(out), n_user, cwd))
    if install and _is_within(out_path, CLAUDE_PROJECTS_DIR):
        print("  已安装到 Claude 项目目录, 在 %s 下运行 claude 后可在历史会话中恢复" % cwd)
        reg_title = title or (first_user_text or "imported from codex"
                              ).strip().splitlines()[0][:60]
        if register_claude_desktop(session_id, reg_title, cwd, n_user):
            print("  已注册 Claude 桌面端, 重启桌面应用后在历史列表可见")
    return out_path


def register_claude_desktop(session_id, title, cwd, human_turns):
    """注册进 Claude 桌面应用的会话列表 (尽力而为, 重启应用后生效).

    桌面应用的历史列表只读 %APPDATA%/Claude/claude-code-sessions/<org>/<user>/
    下的 local_*.json 条目。参照已有条目做模板; 找不到模板时跳过
    (未安装桌面版, 或字段集无从得知)。同一 CLI 会话重复注册时更新原条目。
    """
    root = CLAUDE_DESKTOP_DIR
    if not root or not os.path.isdir(root):
        return False
    try:
        candidates = glob.glob(os.path.join(root, "*", "*", "local_*.json"))
        if not candidates:
            return False
        by_dir = {}
        for p in candidates:
            by_dir.setdefault(os.path.dirname(p), []).append(p)
        target_dir, entries = max(by_dir.items(), key=lambda kv: len(kv[1]))
        out_file = None
        entry = None
        for p in entries:  # 已注册过同一 CLI 会话 -> 更新原条目
            try:
                with open(p, encoding="utf-8") as f:
                    existing = json.load(f)
            except (OSError, json.JSONDecodeError):
                continue
            if existing.get("cliSessionId") == session_id:
                entry, out_file = existing, p
                break
        if entry is None:
            template_path = max(entries, key=os.path.getmtime)
            with open(template_path, encoding="utf-8") as f:
                entry = json.load(f)
            entry["sessionId"] = "local_" + str(uuid.uuid4())
        now_ms = int(datetime.now(timezone.utc).timestamp() * 1000)
        entry.update({
            "cliSessionId": session_id,
            "cwd": cwd, "originCwd": cwd,
            "title": title, "titleSource": "user",
            "createdAt": now_ms, "lastActivityAt": now_ms,
            "lastFocusedAt": now_ms,
            "isArchived": False,
            "completedTurns": human_turns,
            "sessionPermissionUpdates": [],  # 不继承模板会话的权限授权
        })
        if out_file is None:
            out_file = os.path.join(target_dir, entry["sessionId"] + ".json")
        with open(out_file, "w", encoding="utf-8") as f:
            json.dump(entry, f, ensure_ascii=False)
        return True
    except (OSError, json.JSONDecodeError) as exc:
        print("  警告: 未能注册 Claude 桌面端 (%s)" % exc)
        return False


# ---------------------------------------------------------------------------
# Claude -> Codex
# ---------------------------------------------------------------------------

def _win_extended(path):
    """Codex 在 Windows 上以 \\\\?\\ 前缀存路径"""
    if os.name != "nt" or path.startswith("\\\\?\\"):
        return path
    return "\\\\?\\" + path


def register_codex_thread(session_id, title, cwd, rollout_path, preview, start_ts):
    """注册进 Codex 桌面端读取的 state_5.sqlite threads 表 (尽力而为).

    只写 session_index.jsonl 的话, 新版 Codex 桌面端的历史列表看不到会话;
    列表实际读取的是 threads 表。参考已有行做模板, 缺库/缺表时静默跳过。
    """
    import sqlite3
    db = os.path.join(HOME, ".codex", "state_5.sqlite")
    if not os.path.exists(db):
        return False
    try:
        conn = sqlite3.connect(db, timeout=30)
        conn.row_factory = sqlite3.Row
        try:
            cols = {r["name"] for r in conn.execute("PRAGMA table_info(threads)")}
            if not cols:
                return False
            row = conn.execute(
                "SELECT * FROM threads WHERE id <> ? ORDER BY updated_at_ms DESC LIMIT 1",
                (session_id,)).fetchone()
            tmpl = dict(row) if row is not None else {}
            try:
                dt = datetime.fromisoformat(start_ts.replace("Z", "+00:00"))
                created_ms = int(dt.timestamp() * 1000)
            except ValueError:
                created_ms = int(datetime.now(timezone.utc).timestamp() * 1000)
            now = datetime.now(timezone.utc)
            now_s, now_ms = int(now.timestamp()), int(now.timestamp() * 1000)
            values = {
                "id": session_id,
                "rollout_path": _win_extended(rollout_path),
                "created_at": created_ms // 1000,
                "updated_at": now_s,
                "source": tmpl.get("source") or "cli",
                "model_provider": tmpl.get("model_provider") or "anthropic",
                "cwd": _win_extended(cwd),
                "title": title,
                "sandbox_policy": tmpl.get("sandbox_policy") or '{"type":"read-only"}',
                "approval_mode": tmpl.get("approval_mode") or "on-request",
                "tokens_used": 0,
                "has_user_event": 1,
                "archived": 0,
                "cli_version": "session-convert",
                "first_user_message": preview,
                "memory_mode": tmpl.get("memory_mode") or "enabled",
                "model": tmpl.get("model"),
                "created_at_ms": created_ms,
                "updated_at_ms": now_ms,
                "thread_source": "user",
                "preview": preview[:1000],
                "recency_at": now_s,
                "recency_at_ms": now_ms,
                "history_mode": tmpl.get("history_mode") or "legacy",
            }
            usable = {k: v for k, v in values.items() if k in cols}
            exists = conn.execute("SELECT 1 FROM threads WHERE id = ?",
                                  (session_id,)).fetchone() is not None
            if exists:
                sets = ", ".join('"%s" = ?' % k for k in usable if k != "id")
                conn.execute("UPDATE threads SET %s WHERE id = ?" % sets,
                             [v for k, v in usable.items() if k != "id"] + [session_id])
            else:
                names = list(usable)
                conn.execute(
                    "INSERT INTO threads (%s) VALUES (%s)"
                    % (", ".join('"%s"' % n for n in names),
                       ", ".join("?" for _ in names)),
                    [usable[n] for n in names])
            conn.commit()
            return True
        finally:
            conn.close()
    except sqlite3.Error as exc:
        print("  警告: 未能写入 Codex 状态数据库 (%s), 桌面端列表可能看不到该会话" % exc)
        return False


def claude_to_codex(src, out_path=None, install=True, on_conflict="skip"):
    records = read_jsonl(src)

    conv = [r for r in records if r.get("type") in ("user", "assistant")
            and not r.get("isSidechain") and not r.get("isMeta")]
    if not conv:
        sys.exit("没有可转换的对话内容: %s" % src)

    first = conv[0]
    cwd = first.get("cwd", os.getcwd())
    session_id = first.get("sessionId") or str(uuid.uuid4())
    start_ts = first.get("timestamp") or now_iso()

    if install and out_path is None:
        try:
            dt = datetime.fromisoformat(start_ts.replace("Z", "+00:00"))
        except ValueError:
            dt = datetime.now(timezone.utc)
        day_dir = os.path.join(CODEX_SESSIONS_DIR, dt.strftime("%Y"),
                               dt.strftime("%m"), dt.strftime("%d"))
        out_path = os.path.join(
            day_dir, "rollout-%s-%s.jsonl" % (
                dt.strftime("%Y-%m-%dT%H-%M-%S"), session_id))
        out_path, fork_id, skipped = _resolve_output_conflict(
            out_path, on_conflict, lambda: str(uuid.uuid4()),
            lambda target_id: os.path.join(
                day_dir, "rollout-%s-%s.jsonl" % (
                    dt.strftime("%Y-%m-%dT%H-%M-%S"), target_id)))
        if skipped:
            return out_path
        if fork_id:
            session_id = fork_id
    elif out_path is not None:
        out_path, fork_id, skipped = _resolve_output_conflict(
            out_path, on_conflict, lambda: str(uuid.uuid4()))
        if skipped:
            return out_path
        if fork_id:
            session_id = fork_id

    out = []
    first_user_text = None
    img_count = 0
    n_images = 0

    def wrap(ts, rtype, payload):
        out.append({"timestamp": ts, "type": rtype, "payload": payload})

    def save_image(source):
        """把 base64 图片落盘, 供 Codex 界面显示 (模型上下文另走 data URL)"""
        nonlocal img_count
        img_count += 1
        media = source.get("media_type", "image/png")
        ext = {"image/png": ".png", "image/jpeg": ".jpg",
               "image/gif": ".gif", "image/webp": ".webp"}.get(media, ".png")
        img_dir = os.path.join(HOME, ".codex", "bridge-images", session_id)
        os.makedirs(img_dir, exist_ok=True)
        path = os.path.join(img_dir, "img-%03d%s" % (img_count, ext))
        with open(path, "wb") as f:
            f.write(base64.b64decode(source.get("data", "")))
        return path

    # 会话头
    wrap(start_ts, "session_meta", {
        "session_id": session_id, "id": session_id, "timestamp": start_ts,
        "cwd": cwd, "originator": "session_convert",
        "cli_version": "converted-from-claude", "source": "import",
        "thread_source": "user", "model_provider": "anthropic",
    })

    for rec in conv:
        ts = rec.get("timestamp") or now_iso()
        msg = rec.get("message", {})
        content = msg.get("content")

        if rec["type"] == "user":
            if isinstance(content, str):
                if content.lstrip().startswith(CLAUDE_NOISE_PREFIXES):
                    continue
                if first_user_text is None:
                    first_user_text = content
                wrap(ts, "event_msg", {
                    "type": "user_message", "message": content,
                    "images": [], "local_images": [], "audio": [],
                    "local_audio": [], "text_elements": [],
                })
                wrap(ts, "response_item", {
                    "type": "message",
                    "id": "msg_" + uuid.uuid4().hex[:24],
                    "role": "user",
                    "content": [{"type": "input_text", "text": content}],
                })
            elif isinstance(content, list):
                texts, images = [], []
                for block in content:
                    if not isinstance(block, dict):
                        continue
                    bt = block.get("type")
                    if bt == "tool_result":
                        result = block.get("content", "")
                        if isinstance(result, list):
                            result = "".join(
                                b.get("text", "") for b in result
                                if isinstance(b, dict))
                        wrap(ts, "response_item", {
                            "type": "function_call_output",
                            "id": "fco_" + uuid.uuid4().hex[:24],
                            "call_id": block.get("tool_use_id", ""),
                            "output": [{"type": "input_text", "text": str(result)}],
                        })
                    elif bt == "text" and block.get("text", "").strip():
                        texts.append(block["text"])
                    elif bt == "image" and isinstance(block.get("source"), dict) \
                            and block["source"].get("type") == "base64":
                        images.append(block["source"])
                if texts or images:
                    # 用户"图片+文字"消息: event 让 Codex 界面显示,
                    # response_item 用 data URL 让模型上下文携带图片本体
                    n_images += len(images)
                    joined = "\n\n".join(texts)
                    local_paths = [save_image(s) for s in images] if install else []
                    wrap(ts, "event_msg", {
                        "type": "user_message", "message": joined,
                        "images": [], "local_images": local_paths,
                        "audio": [], "local_audio": [], "text_elements": [],
                    })
                    item_content = [
                        {"type": "input_image",
                         "image_url": "data:%s;base64,%s" % (
                             s.get("media_type", "image/png"), s.get("data", ""))}
                        for s in images]
                    if joined:
                        item_content.append({"type": "input_text", "text": joined})
                    wrap(ts, "response_item", {
                        "type": "message",
                        "id": "msg_" + uuid.uuid4().hex[:24],
                        "role": "user",
                        "content": item_content,
                    })

        else:  # assistant
            for block in (content or []):
                if not isinstance(block, dict):
                    continue
                bt = block.get("type")
                if bt == "text" and block.get("text", "").strip():
                    wrap(ts, "event_msg", {
                        "type": "agent_message", "message": block["text"],
                        "phase": "final_answer",
                    })
                    wrap(ts, "response_item", {
                        "type": "message",
                        "id": "msg_" + uuid.uuid4().hex[:24],
                        "role": "assistant",
                        "content": [{"type": "output_text",
                                     "text": block["text"]}],
                        "phase": "final_answer",
                    })
                elif bt == "thinking" and block.get("thinking", "").strip():
                    wrap(ts, "response_item", {
                        "type": "reasoning",
                        "id": "rs_" + uuid.uuid4().hex[:24],
                        "summary": [{"type": "summary_text",
                                     "text": block["thinking"]}],
                    })
                elif bt == "tool_use":
                    wrap(ts, "response_item", {
                        "type": "function_call",
                        "id": "fc_" + uuid.uuid4().hex[:24],
                        "name": block.get("name", "tool"),
                        "arguments": json.dumps(block.get("input", {}),
                                                ensure_ascii=False),
                        "call_id": block.get("id", ""),
                    })

    if out_path is None:
        out_path = os.path.splitext(src)[0] + ".codex.jsonl"
    write_jsonl(out_path, out, overwrite=on_conflict == "overwrite")

    # 追加到 codex 会话索引 + 注册桌面端状态数据库, 让它出现在历史列表里
    registered = False
    if install and _is_within(out_path, CODEX_SESSIONS_DIR):
        title = (first_user_text or "imported from claude").strip()
        title = title.splitlines()[0][:60]
        upsert_codex_index(session_id, title)
        preview = (first_user_text or title).strip()
        registered = register_codex_thread(
            session_id, title, cwd, out_path, preview, start_ts)

    print("Claude -> Codex 转换完成")
    print("  来源: %s" % src)
    print("  输出: %s" % out_path)
    print("  记录: %d 条%s, cwd=%s" % (
        len(out), ", 图片 %d 张" % n_images if n_images else "", cwd))
    if install and _is_within(out_path, CODEX_SESSIONS_DIR):
        print("  已安装到 Codex 会话目录并写入索引%s"
              % (", 已注册桌面端数据库" if registered else ""))
    return out_path


# ---------------------------------------------------------------------------
# OpenCode <-> Codex
# ---------------------------------------------------------------------------

OPENCODE_DB_CANDIDATES = (
    os.path.join(HOME, ".local", "share", "opencode", "opencode.db"),
    os.path.join(os.environ.get("APPDATA", ""), "opencode", "opencode.db"),
    os.path.join(os.environ.get("LOCALAPPDATA", ""), "opencode", "opencode.db"),
)


def find_opencode_db():
    for p in OPENCODE_DB_CANDIDATES:
        if p and os.path.isfile(p):
            return p
    return None


def _opencode_connect(db):
    import sqlite3
    conn = sqlite3.connect("file:%s?mode=ro" % db.replace("\\", "/"), uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def list_opencode_sessions(db, limit=15):
    """[(id, title, directory, time_created_ms)] 按更新时间倒序"""
    conn = _opencode_connect(db)
    try:
        rows = conn.execute(
            """SELECT id, title, directory, time_created FROM session
               WHERE time_archived IS NULL
               ORDER BY time_updated DESC LIMIT ?""", (limit,)).fetchall()
    finally:
        conn.close()
    return [(r["id"], r["title"] or "", r["directory"] or "",
             int(r["time_created"] or 0)) for r in rows]


def load_opencode_conversation(db, session_id):
    """读活库(只读) -> (meta字典, [(role, text, ts_iso)])"""
    conn = _opencode_connect(db)
    try:
        sess = conn.execute("SELECT * FROM session WHERE id = ?",
                            (session_id,)).fetchone()
        if sess is None:
            sys.exit("OpenCode 会话不存在: %s" % session_id)
        messages = conn.execute(
            "SELECT * FROM message WHERE session_id = ? ORDER BY time_created, id",
            (session_id,)).fetchall()
        parts = conn.execute(
            "SELECT * FROM part WHERE session_id = ? ORDER BY time_created, id",
            (session_id,)).fetchall()
    finally:
        conn.close()

    text_by_msg = {}
    for row in parts:
        try:
            data = json.loads(row["data"])
        except (TypeError, json.JSONDecodeError):
            continue
        if isinstance(data, dict) and data.get("type") == "text":
            text = data.get("text")
            if isinstance(text, str) and text.strip():
                text_by_msg.setdefault(row["message_id"], []).append(text.strip())

    conv = []
    for row in messages:
        try:
            data = json.loads(row["data"])
        except (TypeError, json.JSONDecodeError):
            continue
        role = data.get("role") if isinstance(data, dict) else None
        if role not in ("user", "assistant"):
            continue
        text = "\n\n".join(text_by_msg.get(row["id"], [])).strip()
        if not text:
            continue
        ts_ms = int(row["time_created"] or 0)
        ts = datetime.fromtimestamp(ts_ms / 1000, timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z" if ts_ms else now_iso()
        conv.append((role, text, ts))

    meta = {"id": sess["id"], "title": sess["title"] or "",
            "directory": sess["directory"] or os.getcwd(),
            "time_created": int(sess["time_created"] or 0)}
    return meta, conv


def opencode_to_codex(session_id=None, out_path=None, install=True, db=None,
                      on_conflict="skip"):
    db = db or find_opencode_db()
    if not db:
        sys.exit("找不到 OpenCode 数据库 (尝试过: %s)" % "; ".join(OPENCODE_DB_CANDIDATES))
    if session_id is None:  # --latest
        sessions = list_opencode_sessions(db, limit=1)
        if not sessions:
            sys.exit("OpenCode 里没有会话")
        session_id = sessions[0][0]
        print("使用最新 OpenCode 会话: %s" % session_id)
    meta, conv = load_opencode_conversation(db, session_id)
    if not conv:
        sys.exit("没有可转换的对话内容: %s" % session_id)

    cwd = meta["directory"]
    new_id = stable_codex_id(session_id)
    start_ms = meta["time_created"] or int(
        datetime.now(timezone.utc).timestamp() * 1000)
    start_dt = datetime.fromtimestamp(start_ms / 1000, timezone.utc)
    start_ts = start_dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"

    out = [{"timestamp": start_ts, "type": "session_meta", "payload": {
        "session_id": new_id, "id": new_id, "timestamp": start_ts,
        "cwd": cwd, "originator": "session_convert",
        "cli_version": "converted-from-opencode", "source": "import",
        "thread_source": "user", "model_provider": "custom",
    }}]
    first_user_text = None
    for role, text, ts in conv:
        if role == "user":
            if first_user_text is None:
                first_user_text = text
            out.append({"timestamp": ts, "type": "event_msg", "payload": {
                "type": "user_message", "message": text,
                "images": [], "local_images": [], "audio": [],
                "local_audio": [], "text_elements": []}})
            out.append({"timestamp": ts, "type": "response_item", "payload": {
                "type": "message", "id": "msg_" + uuid.uuid4().hex[:24],
                "role": "user",
                "content": [{"type": "input_text", "text": text}]}})
        else:
            out.append({"timestamp": ts, "type": "event_msg", "payload": {
                "type": "agent_message", "message": text, "phase": "final_answer"}})
            out.append({"timestamp": ts, "type": "response_item", "payload": {
                "type": "message", "id": "msg_" + uuid.uuid4().hex[:24],
                "role": "assistant",
                "content": [{"type": "output_text", "text": text}],
                "phase": "final_answer"}})

    if install and out_path is None:
        day_dir = os.path.join(CODEX_SESSIONS_DIR, start_dt.strftime("%Y"),
                               start_dt.strftime("%m"), start_dt.strftime("%d"))
        out_path = os.path.join(day_dir, "rollout-%s-%s.jsonl" % (
            start_dt.strftime("%Y-%m-%dT%H-%M-%S"), new_id))
        out_path, fork_id, skipped = _resolve_output_conflict(
            out_path, on_conflict, lambda: str(uuid.uuid4()),
            lambda target_id: os.path.join(
                day_dir, "rollout-%s-%s.jsonl" % (
                    start_dt.strftime("%Y-%m-%dT%H-%M-%S"), target_id)))
        if skipped:
            return out_path
        if fork_id:
            new_id = fork_id
            out[0]["payload"]["session_id"] = new_id
            out[0]["payload"]["id"] = new_id
    if out_path is None:
        out_path = session_id + ".codex.jsonl"
    elif not install:
        out_path, fork_id, skipped = _resolve_output_conflict(
            out_path, on_conflict, lambda: str(uuid.uuid4()))
        if skipped:
            return out_path
        if fork_id:
            new_id = fork_id
            out[0]["payload"]["session_id"] = new_id
            out[0]["payload"]["id"] = new_id
    write_jsonl(out_path, out, overwrite=on_conflict == "overwrite")

    registered = False
    if install and _is_within(out_path, CODEX_SESSIONS_DIR):
        title = (meta["title"] or first_user_text or "imported from opencode"
                 ).strip().splitlines()[0][:60]
        upsert_codex_index(new_id, title)
        preview = (first_user_text or title).strip()
        registered = register_codex_thread(new_id, title, cwd, out_path,
                                           preview, start_ts)

    print("OpenCode -> Codex 转换完成")
    print("  来源: %s (%s)" % (session_id, db))
    print("  输出: %s" % out_path)
    print("  记录: %d 条, cwd=%s" % (len(out), cwd))
    if install and _is_within(out_path, CODEX_SESSIONS_DIR):
        print("  已安装到 Codex 会话目录并写入索引%s"
              % (", 已注册桌面端数据库" if registered else ""))
    return out_path


def codex_to_opencode(src, out_path=None, on_conflict="skip"):
    """Codex rollout -> OpenCode 导出 JSON (需手动 `opencode import` 导入)"""
    records = read_jsonl(src)
    meta = next((r["payload"] for r in records
                 if r.get("type") == "session_meta"), {})
    cwd = meta.get("cwd", os.getcwd())
    src_id = meta.get("session_id") or meta.get("id") or uuid.uuid4().hex

    conv = []           # (role, text, ts)
    last_human = None
    for rec in records:
        if rec.get("type") != "response_item":
            continue
        p = rec.get("payload", {})
        if p.get("type") != "message":
            continue
        role = p.get("role")
        text = content_to_text(p.get("content"))
        if role not in ("user", "assistant") or not text.strip():
            continue
        if role == "user":
            if text.lstrip().startswith(CONTEXT_PREFIXES):
                continue
            if text.strip() == last_human:
                continue  # 恢复会话产生的重复输入
            last_human = text.strip()
        else:
            last_human = None
        conv.append((role, text, rec.get("timestamp") or now_iso()))
    if not conv:
        sys.exit("没有可转换的对话内容: %s" % src)

    def to_ms(ts):
        try:
            return int(datetime.fromisoformat(
                ts.replace("Z", "+00:00")).timestamp() * 1000)
        except ValueError:
            return int(datetime.now(timezone.utc).timestamp() * 1000)

    new_id = stable_opencode_id(src_id)
    first_user = next((t for r, t, _ in conv if r == "user"), "imported")
    title = first_user.strip().splitlines()[0][:80]
    created = to_ms(conv[0][2])
    messages = []
    parent_id = ""
    for role, text, ts in conv:
        ms = to_ms(ts)
        msg_id = "msg_" + uuid.uuid4().hex[:26]
        if role == "user":
            info = {"id": msg_id, "sessionID": new_id, "role": "user",
                    "time": {"created": ms}, "agent": "session-convert",
                    "model": {"providerID": "session-convert",
                              "modelID": "imported"}}
            parent_id = msg_id
        else:
            info = {"id": msg_id, "sessionID": new_id, "role": "assistant",
                    "time": {"created": ms, "completed": ms},
                    "parentID": parent_id or msg_id,
                    "modelID": "imported", "providerID": "session-convert",
                    "mode": "build", "agent": "session-convert",
                    "path": {"cwd": cwd, "root": cwd}, "cost": 0,
                    "tokens": {"input": 0, "output": 0, "reasoning": 0,
                               "cache": {"read": 0, "write": 0}}}
        messages.append({"info": info, "parts": [{
            "id": "prt_" + uuid.uuid4().hex[:26], "sessionID": new_id,
            "messageID": msg_id, "type": "text", "text": text,
            "time": {"start": ms, "end": ms}}]})

    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:40] or "imported"
    export = {"info": {"id": new_id, "slug": slug, "projectID": "global",
                       "directory": cwd, "title": title,
                       "version": "session-convert",
                       "time": {"created": created,
                                "updated": to_ms(conv[-1][2])}},
              "messages": messages}

    if out_path is None:
        out_path = "%s.opencode.json" % src_id[:8]
    out_path, fork_id, skipped = _resolve_output_conflict(
        out_path, on_conflict,
        lambda: "ses_" + uuid.uuid4().hex[:26],
        lambda target_id: _fork_output_path(out_path, target_id[4:]))
    if skipped:
        return out_path
    if fork_id:
        new_id = fork_id
        export["info"]["id"] = new_id
        for message in export["messages"]:
            message["info"]["sessionID"] = new_id
            for part in message["parts"]:
                part["sessionID"] = new_id
    write_json(out_path, export, overwrite=on_conflict == "overwrite")

    print("Codex -> OpenCode 转换完成")
    print("  来源: %s" % src)
    print("  输出: %s (%d 条消息)" % (out_path, len(messages)))
    print("  OpenCode 不扫描外部文件, 请在终端执行导入:")
    print("    opencode import \"%s\"" % os.path.abspath(out_path))
    return out_path


# ---------------------------------------------------------------------------
# 辅助: 列出会话
# ---------------------------------------------------------------------------

def list_sessions(which):
    if which in ("codex", "all"):
        print("== Codex 会话 (%s) ==" % CODEX_SESSIONS_DIR)
        files = sorted(
            glob.glob(os.path.join(CODEX_SESSIONS_DIR, "**", "rollout-*.jsonl"),
                      recursive=True),
            key=os.path.getmtime, reverse=True)
        for f in files[:20]:
            print("  %s  (%.0f KB)" % (f, os.path.getsize(f) / 1024))
    if which in ("claude", "all"):
        print("== Claude 会话 (%s) ==" % CLAUDE_PROJECTS_DIR)
        files = sorted(
            glob.glob(os.path.join(CLAUDE_PROJECTS_DIR, "*", "*.jsonl")),
            key=os.path.getmtime, reverse=True)
        for f in files[:20]:
            print("  %s  (%.0f KB)" % (f, os.path.getsize(f) / 1024))
    if which in ("opencode", "all"):
        db = find_opencode_db()
        print("== OpenCode 会话 (%s) ==" % (db or "未找到数据库"))
        if db:
            for sid, title, _, ts_ms in list_opencode_sessions(db, limit=20):
                when = datetime.fromtimestamp(ts_ms / 1000).strftime(
                    "%Y-%m-%d %H:%M") if ts_ms else "--"
                print("  %s  [%s] %s" % (sid, when, (title or "(无标题)")[:40]))


# ---------------------------------------------------------------------------
# 交互模式 (双击 exe / 无参数运行)
# ---------------------------------------------------------------------------

def _codex_titles():
    """session_index.jsonl 里的 id -> 标题映射"""
    titles = {}
    if os.path.exists(CODEX_INDEX_FILE):
        for entry in read_jsonl(CODEX_INDEX_FILE):
            if isinstance(entry, dict) and entry.get("id"):
                titles[entry["id"]] = entry.get("thread_name") or ""
    return titles


def _claude_preview(path, limit=200):
    """取 Claude 会话里第一条人类消息作预览"""
    try:
        with open(path, encoding="utf-8") as f:
            for i, line in enumerate(f):
                if i >= limit:
                    break
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if rec.get("type") != "user":
                    continue
                content = rec.get("message", {}).get("content")
                if isinstance(content, str) and content.strip() \
                        and not content.lstrip().startswith(CLAUDE_NOISE_PREFIXES):
                    return content.strip().splitlines()[0]
    except OSError:
        pass
    return ""


def _pick(prompt, count):
    while True:
        raw = input(prompt).strip()
        if raw.lower() in ("q", "quit", "exit"):
            return None
        try:
            n = int(raw)
            if 1 <= n <= count:
                return n - 1
        except ValueError:
            pass
        print("请输入 1-%d 之间的数字, 或 q 退出" % count)


def _pick_codex_file():
    """列最近的 Codex 会话让用户选 -> (路径, 标题) 或 None"""
    files = sorted(
        glob.glob(os.path.join(CODEX_SESSIONS_DIR, "**", "rollout-*.jsonl"),
                  recursive=True),
        key=os.path.getmtime, reverse=True)[:15]
    if not files:
        print("没有找到 Codex 会话 (%s)" % CODEX_SESSIONS_DIR)
        return None
    titles = _codex_titles()
    print()
    infos = []
    for i, f in enumerate(files):
        base = os.path.basename(f)
        # rollout-<时间戳>-<uuid>.jsonl, uuid 是最后 36 位
        sid = base[len("rollout-"):-len(".jsonl")][-36:]
        title = titles.get(sid) or "(无标题)"
        mtime = datetime.fromtimestamp(os.path.getmtime(f)).strftime("%m-%d %H:%M")
        infos.append((f, title))
        print("  %2d. [%s] %s" % (i + 1, mtime, title[:40]))
    print()
    n = _pick("选择要转换的会话 [1-%d]: " % len(infos), len(infos))
    return None if n is None else infos[n]


def interactive_main():
    print("=" * 46)
    print("  Claude / Codex / OpenCode 会话转换工具")
    print("=" * 46)
    print()
    print("  1. Codex    -> Claude    (把 Codex 会话搬进 Claude)")
    print("  2. Claude   -> Codex     (把 Claude 会话搬进 Codex)")
    print("  3. OpenCode -> Codex     (把 OpenCode 会话搬进 Codex)")
    print("  4. Codex    -> OpenCode  (导出文件, 再用 opencode import 导入)")
    print()
    choice = _pick("选择转换方向 [1-4]: ", 4)
    if choice is None:
        return

    if choice == 0:
        picked = _pick_codex_file()
        if picked is None:
            return
        src, title = picked
        codex_to_claude(src, title=title if title != "(无标题)" else None)
        print()
        print("在对应项目目录运行 claude -r, 或重启 Claude 桌面应用即可看到该会话。")
    elif choice == 1:
        files = sorted(
            glob.glob(os.path.join(CLAUDE_PROJECTS_DIR, "*", "*.jsonl")),
            key=os.path.getmtime, reverse=True)[:15]
        if not files:
            print("没有找到 Claude 会话 (%s)" % CLAUDE_PROJECTS_DIR)
            return
        print()
        infos = []
        for i, f in enumerate(files):
            preview = _claude_preview(f) or "(无用户消息)"
            mtime = datetime.fromtimestamp(os.path.getmtime(f)).strftime("%m-%d %H:%M")
            infos.append(f)
            print("  %2d. [%s] %s" % (i + 1, mtime, preview[:40]))
        print()
        n = _pick("选择要转换的会话 [1-%d]: " % len(infos), len(infos))
        if n is None:
            return
        claude_to_codex(infos[n])
        print()
        print("打开 Codex 即可在历史列表中看到该会话。")
    elif choice == 2:
        db = find_opencode_db()
        if not db:
            print("找不到 OpenCode 数据库 (未安装或没用过 OpenCode)")
            return
        sessions = list_opencode_sessions(db)
        if not sessions:
            print("OpenCode 里没有会话")
            return
        print()
        for i, (sid, title, _, ts_ms) in enumerate(sessions):
            when = datetime.fromtimestamp(ts_ms / 1000).strftime("%m-%d %H:%M") \
                if ts_ms else "--"
            print("  %2d. [%s] %s" % (i + 1, when, (title or "(无标题)")[:40]))
        print()
        n = _pick("选择要转换的会话 [1-%d]: " % len(sessions), len(sessions))
        if n is None:
            return
        opencode_to_codex(sessions[n][0], db=db)
        print()
        print("打开 Codex 即可在历史列表中看到该会话。")
    else:
        picked = _pick_codex_file()
        if picked is None:
            return
        src, _ = picked
        desktop = os.path.join(HOME, "Desktop")
        out_dir = desktop if os.path.isdir(desktop) else HOME
        out = codex_to_opencode(src, out_path=os.path.join(
            out_dir, os.path.basename(src)[len("rollout-"):-len(".jsonl")][-36:][:8]
            + ".opencode.json"))
        print()
        print("导出文件已放到: %s" % out)


def _run_interactive():
    try:
        interactive_main()
    except (KeyboardInterrupt, EOFError):
        print()
    except SystemExit as exc:  # codex_to_claude/claude_to_codex 的 sys.exit
        if exc.code:
            print(exc.code)
    except Exception:
        import traceback
        traceback.print_exc()
    finally:
        try:
            input("\n按回车键退出...")
        except (KeyboardInterrupt, EOFError):
            pass


def main():
    if len(sys.argv) == 1:
        _run_interactive()
        return
    ap = argparse.ArgumentParser(
        description="Claude Code 与 Codex 会话互相转换",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p1 = sub.add_parser("codex2claude", help="Codex rollout -> Claude 会话")
    p1.add_argument("input", nargs="?", help="Codex rollout-*.jsonl 文件路径")
    p1.add_argument("--latest", action="store_true", help="使用最新的 Codex 会话")
    p1.add_argument("-o", "--output", help="只输出到该文件, 不安装到 Claude 目录")
    p1.add_argument("--include-context", action="store_true",
                    help="保留 AGENTS.md / 环境上下文等注入消息")
    p1.add_argument("--reasoning", choices=["thinking", "text", "skip"],
                    default="thinking", help="推理摘要的转换方式 (默认 thinking)")
    p1.add_argument("--title", help="设置 Claude 会话标题 (默认无)")
    p1.add_argument("--claude-cwd", help="覆盖会话 cwd, 决定装到哪个 Claude 项目目录")
    p1.add_argument("--on-conflict", choices=CONFLICT_MODES, default="skip",
                    help="目标已存在时: skip(默认), update, overwrite 或 fork")

    p2 = sub.add_parser("claude2codex", help="Claude 会话 -> Codex rollout")
    p2.add_argument("input", nargs="?", help="Claude 会话 .jsonl 文件路径")
    p2.add_argument("--latest", action="store_true", help="使用最新的 Claude 会话")
    p2.add_argument("-o", "--output", help="只输出到该文件, 不安装到 Codex 目录")
    p2.add_argument("--on-conflict", choices=CONFLICT_MODES, default="skip",
                    help="目标已存在时: skip(默认), update, overwrite 或 fork")

    p3 = sub.add_parser("opencode2codex", help="OpenCode 会话 -> Codex rollout")
    p3.add_argument("input", nargs="?", help="OpenCode 会话 id (ses_...)")
    p3.add_argument("--latest", action="store_true", help="使用最新的 OpenCode 会话")
    p3.add_argument("-o", "--output", help="只输出到该文件, 不安装到 Codex 目录")
    p3.add_argument("--db", help="OpenCode 数据库路径 (默认自动探测)")
    p3.add_argument("--on-conflict", choices=CONFLICT_MODES, default="skip",
                    help="目标已存在时: skip(默认), update, overwrite 或 fork")

    p4 = sub.add_parser("codex2opencode",
                        help="Codex rollout -> OpenCode 导出 JSON (之后 opencode import)")
    p4.add_argument("input", nargs="?", help="Codex rollout-*.jsonl 文件路径")
    p4.add_argument("--latest", action="store_true", help="使用最新的 Codex 会话")
    p4.add_argument("-o", "--output", help="导出 JSON 输出路径")
    p4.add_argument("--on-conflict", choices=CONFLICT_MODES, default="skip",
                    help="输出已存在时: skip(默认), update, overwrite 或 fork")

    p5 = sub.add_parser("list", help="列出可转换的会话")
    p5.add_argument("which", nargs="?",
                    choices=["codex", "claude", "opencode", "all"],
                    default="all")

    args = ap.parse_args()

    if args.cmd == "list":
        list_sessions(args.which)
        return

    if args.cmd == "opencode2codex":
        # OpenCode 会话在数据库里, 不走文件路径逻辑
        opencode_to_codex(None if args.latest else args.input,
                          out_path=args.output,
                          install=args.output is None, db=args.db,
                          on_conflict=args.on_conflict)
        return

    if args.latest:
        if args.cmd == "claude2codex":
            src = latest_file(CLAUDE_PROJECTS_DIR, os.path.join("*", "*.jsonl"))
        else:
            src = latest_file(CODEX_SESSIONS_DIR, os.path.join("**", "rollout-*.jsonl"))
        if not src:
            sys.exit("找不到会话文件")
        print("使用最新会话: %s" % src)
    elif args.input:
        src = args.input
        if not os.path.isfile(src):
            sys.exit("文件不存在: %s" % src)
    else:
        sys.exit("请指定输入文件或使用 --latest")

    install = args.output is None
    if args.cmd == "codex2claude":
        codex_to_claude(src, out_path=args.output, install=install,
                        include_context=args.include_context,
                        reasoning_mode=args.reasoning, title=args.title,
                        override_cwd=args.claude_cwd,
                        on_conflict=args.on_conflict)
    elif args.cmd == "codex2opencode":
        codex_to_opencode(src, out_path=args.output,
                          on_conflict=args.on_conflict)
    else:
        claude_to_codex(src, out_path=args.output, install=install,
                        on_conflict=args.on_conflict)


if __name__ == "__main__":
    main()
